// Mocks generated by Mockito 5.4.3 from annotations
// in new_app1/test/test_bird.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:new_app1/bird.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Bird].
///
/// See the documentation for Mockito's code generation for more information.
class MockBird extends _i1.Mock implements _i2.Bird {
  MockBird() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get count => (super.noSuchMethod(
        Invocation.getter(#count),
        returnValue: 0,
      ) as int);

  @override
  set count(int? _count) => super.noSuchMethod(
        Invocation.setter(
          #count,
          _count,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void incrementCounter() => super.noSuchMethod(
        Invocation.method(
          #incrementCounter,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fly() => super.noSuchMethod(
        Invocation.method(
          #fly,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void prey() => super.noSuchMethod(
        Invocation.method(
          #prey,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drink() => super.noSuchMethod(
        Invocation.method(
          #drink,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
